(() => {
  "use strict";
  const tileSets={
    vowels:{label:"Vowels",type:"vowel",items:["a","e","i","o","u","y"]},
    consonants:{label:"Consonants",type:"consonant",items:["b","c","d","f","g","h","j","k","l","m","n","p","qu","r","s","t","v","w","x","y","z"]},
    teams:{label:"Teams",type:"team",items:["sh","ch","th","wh","ph","ck","ng","tch","dge","ai","ay","ee","ea","oa","ow","oi","oy","ar","or","er","ir","ur"]},
    chunks:{label:"Chunks",type:"chunk",items:["ild","old","ind","ost","unk","all","ank","ink","onk","ung"]},
    prefixes:{label:"Prefixes",type:"prefix",items:["un","re","dis","mis","pre"]},
    suffixes:{label:"Suffixes",type:"suffix",items:["s","es","ed","ing","er","est","ly","ful","less"]},
    special:{label:"Special",type:"special",items:["e","'","-","•","/"]}
  };
  const board=document.getElementById("board"),emptyState=document.getElementById("emptyState"),tileCount=document.getElementById("tileCount"),allTileGroups=document.getElementById("allTileGroups"),tileSearch=document.getElementById("tileSearch"),undoBtn=document.getElementById("undoBtn"),redoBtn=document.getElementById("redoBtn"),duplicateBtn=document.getElementById("duplicateBtn"),deleteBtn=document.getElementById("deleteBtn");
  let selectedTile=null,dragState=null,nextId=1,history=[],historyIndex=-1,suppressSnapshot=false;
  function renderAllTiles(){const search=tileSearch.value.trim().toLowerCase();allTileGroups.innerHTML="";Object.values(tileSets).forEach(group=>{const matches=group.items.filter(t=>t.toLowerCase().includes(search));if(search&&!matches.length)return;const section=document.createElement("section");section.className="tile-group";const h=document.createElement("h3");h.textContent=group.label;const tray=document.createElement("div");tray.className="group-tray";matches.forEach(text=>tray.appendChild(makeLibraryTile(text,group.type)));section.append(h,tray);allTileGroups.appendChild(section)});if(!allTileGroups.children.length){const p=document.createElement("p");p.textContent="No matching tiles.";p.style.color="#758179";allTileGroups.appendChild(p)}}
  function makeLibraryTile(text,type){const el=document.createElement("button");el.type="button";el.className=`tile library-tile ${type}`;el.textContent=text;if(text==="y"){const job=type==="vowel"?"vowel":"consonant";el.title=`y acting as a ${job}`;el.setAttribute("aria-label",`y acting as a ${job}`)}else el.title=`Add ${text}`;el.addEventListener("click",()=>{const offset=24*(board.querySelectorAll(".board-tile").length%8);addBoardTile(text,type,60+offset,80+offset,false);snapshot()});return el}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
  function addBoardTile(text,type,x,y,selected=true){const el=document.createElement("div");el.className=`tile board-tile ${type}`;el.textContent=text;el.dataset.text=text;el.dataset.type=type;el.dataset.tileId=String(nextId++);el.style.left=`${Math.max(0,x)}px`;el.style.top=`${Math.max(0,y)}px`;el.tabIndex=0;el.addEventListener("pointerdown",beginDrag);el.addEventListener("click",e=>{e.stopPropagation();selectTile(el)});el.addEventListener("dblclick",e=>{e.preventDefault();e.stopPropagation();selectTile(el);duplicateSelected()});board.appendChild(el);if(selected)selectTile(el);updateUI();return el}
  function selectTile(el){if(selectedTile&&selectedTile!==el)selectedTile.classList.remove("selected");selectedTile=el;if(selectedTile)selectedTile.classList.add("selected");updateUI()}
  function deselect(){if(selectedTile)selectedTile.classList.remove("selected");selectedTile=null;updateUI()}
  function beginDrag(e){if(e.button!==undefined&&e.button!==0)return;const el=e.currentTarget;e.preventDefault();e.stopPropagation();selectTile(el);const r=el.getBoundingClientRect();dragState={pointerId:e.pointerId,el,dx:e.clientX-r.left,dy:e.clientY-r.top,startLeft:parseFloat(el.style.left)||0,startTop:parseFloat(el.style.top)||0};el.classList.add("dragging");try{el.setPointerCapture(e.pointerId)}catch{}el.addEventListener("pointermove",dragMove);el.addEventListener("pointerup",endDrag);el.addEventListener("pointercancel",endDrag)}
  function dragMove(e){if(!dragState||e.pointerId!==dragState.pointerId)return;e.preventDefault();const {el,dx,dy}=dragState,r=board.getBoundingClientRect(),maxX=Math.max(0,board.clientWidth-el.offsetWidth),maxY=Math.max(0,board.clientHeight-el.offsetHeight);el.style.left=`${clamp(e.clientX-r.left-dx,0,maxX)}px`;el.style.top=`${clamp(e.clientY-r.top-dy,0,maxY)}px`}
  function endDrag(){if(!dragState)return;const {el,startLeft,startTop,pointerId}=dragState;el.classList.remove("dragging");el.removeEventListener("pointermove",dragMove);el.removeEventListener("pointerup",endDrag);el.removeEventListener("pointercancel",endDrag);try{if(el.hasPointerCapture(pointerId))el.releasePointerCapture(pointerId)}catch{}const changed=Math.abs((parseFloat(el.style.left)||0)-startLeft)>.5||Math.abs((parseFloat(el.style.top)||0)-startTop)>.5;dragState=null;if(changed)snapshot()}
  function duplicateSelected(){if(!selectedTile)return;addBoardTile(selectedTile.dataset.text,selectedTile.dataset.type,(parseFloat(selectedTile.style.left)||0)+70,(parseFloat(selectedTile.style.top)||0)+70,true);snapshot()}
  function deleteSelected(){if(!selectedTile)return;selectedTile.remove();selectedTile=null;updateUI();snapshot()}
  function clearBoard(){if(!board.querySelector(".board-tile"))return;if(!confirm("Clear every tile from the board?"))return;board.querySelectorAll(".board-tile").forEach(el=>el.remove());selectedTile=null;updateUI();snapshot()}
  function serializeBoard(){return [...board.querySelectorAll(".board-tile")].map(el=>({text:el.dataset.text,type:el.dataset.type,left:parseFloat(el.style.left)||0,top:parseFloat(el.style.top)||0}))}
  function restoreBoard(data){suppressSnapshot=true;board.querySelectorAll(".board-tile").forEach(el=>el.remove());selectedTile=null;if(Array.isArray(data))data.forEach(i=>addBoardTile(String(i.text??""),String(i.type??"consonant"),Number(i.left??0),Number(i.top??0),false));suppressSnapshot=false;updateUI()}
  function snapshot(){if(suppressSnapshot)return;const state=JSON.stringify(serializeBoard());if(historyIndex>=0&&history[historyIndex]===state){updateUI();return}history=history.slice(0,historyIndex+1);history.push(state);historyIndex=history.length-1;if(history.length>60){history.shift();historyIndex--}updateUI()}
  function undo(){if(historyIndex<=0)return;historyIndex--;restoreBoard(JSON.parse(history[historyIndex]));updateUI()}
  function redo(){if(historyIndex>=history.length-1)return;historyIndex++;restoreBoard(JSON.parse(history[historyIndex]));updateUI()}
  function updateUI(){const count=board.querySelectorAll(".board-tile").length;tileCount.textContent=`${count} ${count===1?"tile":"tiles"}`;emptyState.classList.toggle("hidden",count>0);undoBtn.disabled=historyIndex<=0;redoBtn.disabled=historyIndex<0||historyIndex>=history.length-1;duplicateBtn.disabled=!selectedTile;deleteBtn.disabled=!selectedTile}
  tileSearch.addEventListener("input",renderAllTiles);board.addEventListener("pointerdown",e=>{if(e.target===board)deselect()});undoBtn.addEventListener("click",undo);redoBtn.addEventListener("click",redo);duplicateBtn.addEventListener("click",duplicateSelected);deleteBtn.addEventListener("click",deleteSelected);document.getElementById("clearBtn").addEventListener("click",clearBoard);document.getElementById("saveBtn").addEventListener("click",()=>{localStorage.setItem("rootroom-tile-room-board",JSON.stringify(serializeBoard()));alert("Board saved in this browser.")});document.getElementById("loadBtn").addEventListener("click",()=>{const raw=localStorage.getItem("rootroom-tile-room-board");if(!raw)return alert("No saved board was found in this browser.");try{restoreBoard(JSON.parse(raw));snapshot()}catch{alert("The saved board could not be loaded.")}});document.getElementById("fullscreenBtn").addEventListener("click",async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}});document.addEventListener("keydown",e=>{const tag=document.activeElement?.tagName,typing=tag==="INPUT"||tag==="TEXTAREA";if(!typing&&(e.key==="Delete"||e.key==="Backspace")&&selectedTile){e.preventDefault();deleteSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"&&!e.shiftKey){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&(e.key.toLowerCase()==="y"||(e.shiftKey&&e.key.toLowerCase()==="z"))){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"&&selectedTile){e.preventDefault();duplicateSelected()}});renderAllTiles();snapshot();updateUI();
})();